# Knowledge Graph Configuration

knowledge_graph:
  version: 2.1.0

# Entity Extraction Configuration
entity_extraction:
  models:
    spacy:
      model_name: en_core_web_trf
      confidence_threshold: 0.7
    huggingface:
      model_name: allenai/scibert_scivocab_uncased
      confidence_threshold: 0.6
    visual:
      ocr_enabled: true
      object_detection_enabled: false
  multi_modal:
    enabled: true
    strategies: 
      - textual
      - visual
      - contextual
    reconciliation:
      deduplication_threshold: 0.8
      confidence_threshold: 0.7

# Domain-Specific Evaluation Configuration
domain_evaluation:
  enabled: true
  metrics:
    - entity_recognition
    - relationship_inference
    - semantic_similarity
    - contextual_coherence
    
  evaluation_strategies:
    precision_recall_balance: 0.5
    semantic_similarity_weight: 0.3
    contextual_coherence_weight: 0.2

# Cross-Domain Reasoning Configuration
cross_domain_reasoning:
  enabled: true
  domains:
    - physics
    - technology
    - engineering
    
  reasoning_strategies:
    - logical_inference
    - hypothesis_generation
    - probabilistic_reasoning
    
  inference_parameters:
    similarity_threshold: 0.6
    max_inference_depth: 3
    confidence_threshold: 0.7

# Relationship Mapping Configuration
relationship_mapping:
  confidence_scoring:
    base_weight: 0.5
    semantic_proximity_weight: 0.3
    type_compatibility_weight: 0.2
  max_relationship_distance: 3
  pruning_threshold: 0.4

# Graph Construction Configuration
graph_construction:
  versioning:
    max_versions: 10
    auto_prune: true
  visualization:
    enabled: true
    output_format: 
      - networkx
      - graphviz
      - json

# Schema Evolution Configuration
schema_evolution:
  enabled: true
  versioning:
    max_versions: 10
    backup_frequency: daily
    
  update_strategies:
    - incremental
    - semantic_inference
    - backward_compatible
    
  reconciliation:
    deduplication_threshold: 0.85
    type_inference_confidence: 0.75

# Performance and Resource Configuration
performance:
  max_concurrent_tasks: 8
  memory_limit_mb: 2048
  cache_enabled: true
  cache_expiry_minutes: 60
  memory_threshold: 0.8
  processing_timeout: 300  # seconds

# Logging Configuration
logging:
  level: DEBUG
  console_output: true
  file_output: true
  output_formats:
    - console
    - file
  log_dir: logs/knowledge_graph
  log_retention_days: 30

# Experimental Features
experimental:
  quantum_inspired_reasoning: false
  advanced_embedding_techniques: true
