name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort mypy pylint pytest-cov
        pip install -r requirements.txt
        
    - name: Check formatting with Black
      run: |
        black --check src/ tests/
        
    - name: Check imports with isort
      run: |
        isort --check-only src/ tests/
        
    - name: Type checking with mypy
      run: |
        mypy src/
        
    - name: Lint with pylint
      run: |
        pylint src/ tests/
        
    - name: Run tests with coverage
      run: |
        pytest --cov=src/ tests/ --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
        
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
    - name: Check for code complexity
      run: |
        radon cc src/ -a -s
        xenon --max-absolute A --max-modules A --max-average A src/
        
    - name: Generate quality report
      run: |
        mkdir -p reports
        black --check src/ tests/ > reports/formatting.txt || true
        pylint src/ tests/ > reports/linting.txt || true
        radon cc src/ -a -s > reports/complexity.txt
        
    - name: Upload quality report
      uses: actions/upload-artifact@v2
      with:
        name: code-quality-report
        path: reports/
